version: '3.8'

services:
  dev-stock-analyser:
    image: 
    container_name: stock-analyser-dev-container
    volumes:
      - ${DEV_CONFIG_PATH}:/app/config/config.json
      - ${AWS_CREDANTIALS_PATH}:/root/.aws
    pull_policy: always
