version: '3.8'

services:
  dev-stock-analyser:
    image: 108782078484.dkr.ecr.eu-north-1.amazonaws.com/stock-analyser:0.0.1-20250312-e049738
    container_name: stock-analyser-prod-container
    volumes:
      - ${PROD_CONFIG_PATH}:/app/config/config.json
      - ${AWS_CREDANTIALS_PATH}:/root/.aws
    pull_policy: always
